package dev.kartik.accessmanager.vpn.relay

import dev.kartik.accessmanager.vpn.packet.RawPacket
import kotlinx.coroutines.flow.Flow

/**
 * An abstraction for a userspace network core (e.g., lwIP, tun2socks, or a custom stack).
 *
 * This allows the AccessManager to decouple policy evaluation (which happens in Kotlin)
 * from the actual transport of bytes (which may happen via a JNI C/C++ library later).
 */
interface RelayEngine {

    /**
     * Called to initialize the relay backend and bind to any necessary resources.
     */
    fun start()

    /**
     * Enqueues an uplink packet that has been EXPLICITLY ALLOWED by the DecisionEngine.
     * The relay engine is responsible for maintaining the TCP/UDP state and sending
     * the payload to the remote internet socket.
     */
    suspend fun enqueueUplink(packet: RawPacket)

    /**
     * A continuous stream of raw packets generated by the relay engine (e.g., payloads
     * arriving from the remote internet socket wrapped in locally synthesized TCP/IP headers)
     * that must be written directly back to the TUN interface.
     */
    val downlinkPackets: Flow<RawPacket>

    /**
     * Gracefully tears down the relay resources and closes all outbound sockets.
     */
    fun stop()
}
