build:
  maxIssues: 0

complexity:
  LongMethod:
    threshold: 60
  LongParameterList:
    functionThreshold: 8
    constructorThreshold: 8
    ignoreAnnotated:
      - "Composable"
  TooManyFunctions:
    thresholdInFiles: 15
    thresholdInClasses: 15
    thresholdInInterfaces: 15
    thresholdInObjects: 15
    thresholdInEnums: 15

style:
  MagicNumber:
    ignorePropertyDeclaration: true
    ignoreAnnotation: true
    ignoreCompanionObjectPropertyDeclaration: true
    ignoreHashCodeFunction: true
    ignoreEnums: true
    ignoreNamedArgument: true
  MaxLineLength:
    maxLineLength: 120
  WildcardImport:
    active: true
  ReturnCount:
    max: 4

naming:
  FunctionNaming:
    ignoreAnnotated:
      - "Composable"

formatting:
  MaximumLineLength:
    maxLineLength: 120
